// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	context "context"

	mlm "github.com/Montelibero/mlm"
	mock "github.com/stretchr/testify/mock"
)

// RecommenderFetcher is an autogenerated mock type for the RecommenderFetcher type
type RecommenderFetcher struct {
	mock.Mock
}

type RecommenderFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *RecommenderFetcher) EXPECT() *RecommenderFetcher_Expecter {
	return &RecommenderFetcher_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function with given fields: ctx
func (_m *RecommenderFetcher) Fetch(ctx context.Context) (*mlm.RecommenderFetchResult, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 *mlm.RecommenderFetchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*mlm.RecommenderFetchResult, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *mlm.RecommenderFetchResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mlm.RecommenderFetchResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecommenderFetcher_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type RecommenderFetcher_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RecommenderFetcher_Expecter) Fetch(ctx interface{}) *RecommenderFetcher_Fetch_Call {
	return &RecommenderFetcher_Fetch_Call{Call: _e.mock.On("Fetch", ctx)}
}

func (_c *RecommenderFetcher_Fetch_Call) Run(run func(ctx context.Context)) *RecommenderFetcher_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *RecommenderFetcher_Fetch_Call) Return(_a0 *mlm.RecommenderFetchResult, _a1 error) *RecommenderFetcher_Fetch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RecommenderFetcher_Fetch_Call) RunAndReturn(run func(context.Context) (*mlm.RecommenderFetchResult, error)) *RecommenderFetcher_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// NewRecommenderFetcher creates a new instance of RecommenderFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecommenderFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *RecommenderFetcher {
	mock := &RecommenderFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
